---
services:
  redis:
    image: redis:7.0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6

  kafka:
    image: apache/kafka:4.1.1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_HOSTS: ${KAFKA_ADVERTISED_HOSTS:-192.168.1.1}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${KAFKA_ADVERTISED_HOSTS}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_MS: 86400000
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1",
        ]
      interval: 20s
      timeout: 10s
      retries: 6

  clamav:
    image: clamav/clamav:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "clamdscan --version >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10
    user: clamav
    entrypoint: ["/init-unprivileged"]
    deploy:
      replicas: 2

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    volumes:
      - minio_data:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sSf http://localhost:9000/minio/health/live >/dev/null || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 6

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
      sleep 10 &&
      mc alias set local http://minio:9000 minioadmin minioadmin &&
      mc mb -p local/scans || echo 'Bucket files already exists'
      "

  scanner:
    build:
      context: .
    depends_on:
      - kafka
      - clamav
      - minio-init
    environment:
      KAFKA_SERVER: kafka:9092
      KAFKA_INPUT_TOPIC: files_to_scan
      KAFKA_OUTPUT_TOPIC: scan_results
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      CLAMD_HOSTS: scanasservice-clamav-1:3310,scanasservice-clamav-2:3310
      WORKER_POOL: 8
      LOG_LEVEL: INFO
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"

volumes:
  minio_data:
