---
services:
  kafka:
    image: apache/kafka:4.1.1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_MS: 86400000
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1",
        ]
      interval: 20s
      timeout: 10s
      retries: 6

  clamav:
    image: clamav/clamav:1.5.1
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "clamdscan --version >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10
    user: clamav
    entrypoint: ["/init-unprivileged"]
    deploy:
      replicas: 2

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    volumes:
      - minio_data:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sSf http://localhost:9000/minio/health/live >/dev/null || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 6

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
      sleep 10 &&
      mc alias set local http://minio:9000 minioadmin minioadmin &&
      mc mb -p local/scans || echo 'Bucket files already exists' &&
      mc admin config set myminio notify_webhook:1 endpoint="http://localhost:8000/minio/events" queue_limit="10000" queue_dir="/tmp/minio-queue"
      mc admin config set myminio notify_sqs:1 enable="on" queue_url="http://localhost:9324/queue/myqueue" access_key="minioaccess" secret_key="miniosecret" queue_dir="/tmp/minio-queue"
      "

  scanner:
    build:
      context: .
    depends_on:
      - redis
      - kafka
      - clamav
      - minio-init
    environment:
      CLAMD_HOSTS: scanasservice-clamav-1:3310,scanasservice-clamav-2:3310
      KAFKA_INPUT_TOPIC: files_to_scan
      KAFKA_OUTPUT_TOPIC: scan_results
      KAFKA_SERVERS: kafka:9092
      LOG_LEVEL: INFO
      S3_ACCESS_KEY: minioadmin
      S3_ENDPOINT_URL: http://minio:9000
      S3_SECRET_KEY: minioadmin
      MAX_CONCURRENT_SCANS: 8
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sSf http://localhost:8000/heartbeat >/dev/null || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 6
volumes:
  minio_data:
